# Generated by Django 5.2.6 on 2025-10-06 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionInterna', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichaamortiguador',
            name='valorreferencia',
        ),
        migrations.AddField(
            model_name='fichaamortiguador',
            name='valor_maximo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fichaamortiguador',
            name='valor_minimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='observacion',
            name='valordiagrama',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='stockreservado',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MaterialFichaAmortiguador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadrecomendada', models.BigIntegerField()),
                ('fichaamortiguador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionInterna.fichaamortiguador')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionInterna.material')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materiales', models.TextField(help_text='JSON list of missing materials with required/available')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionInterna.tarea')),
            ],
        ),
    ]
