# Generated by Django 5.2.6 on 2025-10-10 15:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionInterna', '0003_alter_notificacion_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='nombre',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='material',
            name='unidad',
            field=models.CharField(default='unidad', max_length=100),
        ),
        migrations.AlterField(
            model_name='material',
            name='stockActual',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='stockMinimo',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='stockreservado',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('cantidad', models.BigIntegerField()),
                ('proveedor', models.CharField(blank=True, max_length=200)),
                ('observacion', models.TextField(blank=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionInterna.material')),
            ],
        ),
    ]
