# Generated by Django 5.2.6 on 2025-10-31 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionInterna', '0004_material_nombre_material_unidad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operario',
            name='role',
            field=models.CharField(choices=[('operario', 'Operario'), ('encargado', 'Encargado')], default='operario', max_length=20),
        ),
        migrations.AddField(
            model_name='operario',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operario', to=settings.AUTH_USER_MODEL),
        ),
    ]
