# Generated by Django 5.2.6 on 2025-10-31 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionInterna', '0005_operario_role_operario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operario',
            name='role',
            field=models.CharField(choices=[('operario', 'Operario'), ('encargado', 'Encargado'), ('encargado_materiales', 'Encargado de Materiales')], default='operario', max_length=20),
        ),
    ]
