# Generated by Django 5.2.6 on 2025-09-15 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fichaamortiguador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombregenerico', models.CharField(max_length=100)),
                ('nroseriegenerico', models.CharField(max_length=100)),
                ('valorreferencia', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('stockActual', models.BigIntegerField()),
                ('stockMinimo', models.BigIntegerField()),
                ('stockreservado', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.BigIntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Amortiguador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nroSerieamortiguador', models.BigIntegerField()),
                ('tipo', models.CharField(max_length=100)),
                ('configuracion', models.CharField(default='Sin configurar', max_length=100)),
                ('fichaamortiguador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionInterna.fichaamortiguador')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaingreso', models.DateField(auto_now_add=True)),
                ('horaingreso', models.TimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=100)),
                ('fechaSalidaEstimada', models.DateField(blank=True, null=True)),
                ('fechaSalidaReal', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionInterna.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionInterna.material')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionInterna.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20)),
                ('prioridad', models.CharField(max_length=20)),
                ('fechaAsignacion', models.DateField(auto_now_add=True)),
                ('fechaLimite', models.DateField(blank=True, null=True)),
                ('tipoTarea', models.CharField(blank=True, max_length=100, null=True)),
                ('amortiguador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionInterna.amortiguador')),
                ('operario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionInterna.operario')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionInterna.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaobservacion', models.DateField(auto_now_add=True)),
                ('horaobservacion', models.TimeField(auto_now_add=True)),
                ('tipoobservacion', models.CharField(max_length=100)),
                ('infoobservacion', models.TextField(blank=True, null=True)),
                ('amortiguador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionInterna.amortiguador')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionInterna.tarea')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockrecomendado', models.BigIntegerField()),
                ('stockusado', models.BigIntegerField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionInterna.material')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionInterna.tarea')),
            ],
        ),
    ]
