# Generated by Django 5.2.6 on 2025-10-06 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionInterna', '0002_remove_fichaamortiguador_valorreferencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionInterna.tarea'),
        ),
    ]
